[package]
name = "echochain"
version = "0.1.0"
edition = "2021"

[dependencies]
ink = { version = "4.0.0-beta", default-features = false }

[lib]
name = "echochain"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]
std = [
    "ink/std",
]
